# Site settings
title: Tales of Murder
email: talesofmurderpress@gmail.com
description: A murder mystery short story &amp; novel site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://talesofmurder.com" # the base hostname & protocol for your site
twitter_username: talesofmurder
github_username:  flaturtha
locale: en_US

# Site Owner
# owner:
# 	name: Rich Cook
# 	avatar:
# 	email: talesofmurderpress@gmail.com
# 	google:
# 		plus: talesofmurderpress
# 		analytics: UA-42672955-1
# 		verify:


# Build settings
permalink: /:categories/:title/
markdown: kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
